### ISSUE TITLE
Games do annoying viewport resizing when embedded in a minicade on mobile

### ISSUE THREAD

**Issue by toolness** [toolness/mobile-microgame-maker#41]
For instance, on my iPhone, the following wreaks havoc on my viewport as minicade switches between the metagame and the minigame:

http://minica.de/f/catch-the-yellow-monster

Specifically, it looks like this:

![image1](https://cloud.githubusercontent.com/assets/124687/5990781/ca4dea28-a990-11e4-8be6-9af3185abdc3.PNG)

**Comment by toolness** [comment]
Adding the following CSS to the export template seems to fix it on the iPhone:

``` css
@media (max-width: 320px) {
  #phaser-holder {
    max-width: 320px;
  }
}
```

Not a huge fan of the fix, but it's the only one I've found so far.
